name: pyfla
channels:
  - defaults
dependencies:
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py36_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - ncurses=6.1=he6710b0_1
  - openssl=1.1.1b=h7b6447c_1
  - pip=19.0.3=py36_0
  - python=3.6.8=h0371630_0
  - readline=7.0=h7b6447c_5
  - setuptools=40.8.0=py36_0
  - sqlite=3.27.2=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.33.1=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.7.1
    - astor==0.7.1
    - chardet==3.0.4
    - click==7.0
    - dominate==2.3.5
    - flask==1.0.2
    - flask-bootstrap==3.3.7.1
    - flask-wtf==0.14.2
    - gast==0.2.2
    - gevent==1.4.0
    - greenlet==0.4.15
    - grpcio==1.19.0
    - gunicorn==19.9.0
    - h5py==2.9.0
    - idna==2.8
    - itsdangerous==1.1.0
    - jinja2==2.10.1
    - keras==2.2.4
    - keras-applications==1.0.7
    - keras-preprocessing==1.0.9
    - markdown==3.1
    - markupsafe==1.1.1
    - mock==2.0.0
    - numpy==1.16.2
    - pbr==5.1.3
    - pillow==6.0.0
    - protobuf==3.7.1
    - pyyaml==5.1
    - requests==2.21.0
    - scipy==1.2.1
    - six==1.12.0
    - tensorboard==1.12.2
    - tensorflow-estimator==1.13.0
    - tensorflow-gpu==1.12.0
    - termcolor==1.1.0
    - urllib3==1.24.1
    - visitor==0.1.3
    - werkzeug==0.15.2
    - wtforms==2.2.1
prefix: /home/kevin/anaconda3/envs/pyfla

